### ISSUE TITLE
⭐️ Create Vue Components for all Field Types

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#132]
- [ ] #118 Make "Geolocation" field (traditional)
 - [x] #119 Make "Embed" / "Video" field (traditional)
 - [ ] #120 Make "Select" field to select items from other content.
 - [ ] #123 Make "Geolocation" a Vue component.
 - [ ] #124 Make "Embed" a Vue component.
 - [x] #133 Make "Multi-select" Vue Component
 - [ ] #36 VC | Checkbox Component
 - [x] #49 After uploading an image, the filename should be updated

**Comment by bobdenotter** [comment]
@marcingajda I'm going to bump this to "alpha 3". Let us know when you're going to work on these, and if you need a hand! :-)

**Comment by marcingajda** [comment]
@bobdenotter Hi, sorry for responding so late. I will start working on this this week.

**Comment by bobdenotter** [comment]
Bumping this to a later version. If there's a valid usecase, we can bump it higher on the priority list again.

**Comment by bobdenotter** [comment]
The fields we have work. I don't see a need to keep this on the list separately. Some fields need work (Geo, for example), but we'll handle them as needed.
