### ISSUE TITLE
⭐️ Make "Extensions"

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#134]
Things to do: 

- [x] Make extensions 'autoload' as a compiler pass
- [x] Make extensions call their 'initialising' method after booting
- [x] Make possible for extensions to have their own config file
- [x] Make extension add widgets/snippets
- [x] Make extensions add Twig funcions & filters
- [ ] Provide things like `Request`, `Response`, `Config` in extensions
- [ ] Make Autowiring work for extensions
- [x] Make command for `extensions:list`
- [ ] Make command for `extensions:info`
- [ ] Make command for `extensions:enable`
- [ ] Make command for `extensions:disable`
- [x] Make controller / UI screen in backend
- [ ] Create `make:extension` command
- [ ] Make it so extensions can add FieldTypes.

**Comment by bobdenotter** [comment]
Note: This package might be convenient: 

 - https://www.reddit.com/r/PHP/comments/cl206o/new_package_composer_helper_classes_for_finding/
 - https://github.com/drupol/composer-packages

**Comment by drupol** [comment]
> Note: This package might be convenient:
> 
>     * https://www.reddit.com/r/PHP/comments/cl206o/new_package_composer_helper_classes_for_finding/
> 
>     * https://github.com/drupol/composer-packages

Hey cool, thanks for this! I built this package especially for that purpose. Allowing people to easily find package extensions :-)

Thanks!!!

**Comment by bobdenotter** [comment]
@drupol If i bump into any issues implementing it, i'll be sure to reach out! 👍

**Comment by bobdenotter** [comment]
Closing, see #492
