### ISSUE TITLE
Smoother onboarding experience

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#2119]
- [ ] Revisit installation guide, describe how to set up composer.
- [ ] After install, tell people to setup bolt (`bin/console bolt:setup`)
- [ ] Instruct people how to start their server and go to the homepage
- [ ] On the homepage, give some basic info and describe how to go to Backend, make some simple changes to get started. Maybe include links to Bolt Tips / Community / Slack for further help?

**Comment by I-Valchev** [comment]
#2225 fixes the 4th checkbox (homepage instructions)
